apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: test-k8s-cluster
  region: us-east-1

nodeGroups:
  - name: ng-m5-xlarge
    instanceType: m5.xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 2