apiVersion: v1
kind: Service
metadata:
  name: clothing-classifier
spec:
  type: LoadBalancer
  selector:
    app: clothing-classifier-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080